version: 2

sources:
  - name: etl_dbt_eedb011.banks
    description: My project with DBT
    loader: snowflake
    schema: DBT_RAW
    tables:
      - name: banks
        description: Banks data
        loaded_at_field: _load_time
        file_format: parquet
        location: seeds/banks