WITH f_banks AS (
    SELECT * FROM {{ref('banks')}}
)

SELECT
    SEGMENTO
    ,CNPJ
    ,NOME
    ,REPLACE(NOME,' - PRUDENCIAL','') AS NOME_AJUSTADO
FROM f_banks
WHERE
    ROW_NUMBER() OVER(PARTITION BY(CNPJ) ORDER BY PrudencialCheck ASC) = 1 AND
    CASE WHEN NOME LIKE '%PRUDENCIAL%' THEN 1 ELSE 0 END  <= 1